### ISSUE TITLE
0xff-bytes in first cache line of unaligned memory writes

### ISSUE THREAD

**Issue by rs22** [OpenCAPI/ocse#10]
I have an AFU (oc-accel action) that performs selective writes to host memory with single-byte granularity.

While this works fine on the actual FPGA, the ocse simulation always replaces writes in the first transfer with 0xFF bytes.

To illustrate: Given two aligned buffers (`source` and `destination`, `destination` is zero-ed), my AFU performs a copy from offset 2 in `source` to offset 2 in `destination` with a length of 128 bytes. Curiously, the issue seems to be aligned to a 64-byte boundary (half of a cache line). This is the outcome:

```
Source                                           | Destination
00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f  | 00 00 ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
10 11 12 13 14 15 16 17 18 19 1a 1b 1c 1d 1e 1f  | ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
20 21 22 23 24 25 26 27 28 29 2a 2b 2c 2d 2e 2f  | ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
30 31 32 33 34 35 36 37 38 39 3a 3b 3c 3d 3e 3f  | ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff 
40 41 42 43 44 45 46 47 48 49 4a 4b 4c 4d 4e 4f  | 40 41 42 43 44 45 46 47 48 49 4a 4b 4c 4d 4e 4f 
50 51 52 53 54 55 56 57 58 59 5a 5b 5c 5d 5e 5f  | 50 51 52 53 54 55 56 57 58 59 5a 5b 5c 5d 5e 5f 
60 61 62 63 64 65 66 67 68 69 6a 6b 6c 6d 6e 6f  | 60 61 62 63 64 65 66 67 68 69 6a 6b 6c 6d 6e 6f 
70 71 72 73 74 75 76 77 78 79 7a 7b 7c 7d 7e 7f  | 70 71 72 73 74 75 76 77 78 79 7a 7b 7c 7d 7e 7f 
80 81 82 83 84 85 86 87 88 89 8a 8b 8c 8d 8e 8f  | 80 81 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
90 91 92 93 94 95 96 97 98 99 9a 9b 9c 9d 9e 9f  | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
a0 a1 a2 a3 a4 a5 a6 a7 a8 a9 aa ab ac ad ae af  | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
b0 b1 b2 b3 b4 b5 b6 b7 b8 b9 ba bb bc bd be bf  | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```

The README states as a known limitation that 'ocxl_lpc_read and _write require offsets and sizes that are naturally aligned.' -- is this related? This used to work in PSLSE... cc @bmesnet

**Comment by bmesnet** [comment]
Hi @rs22 
We have found the issue and corrected it. 
OCSE fills the invalid bytes of partial reads with 0xFF while P9 fills it with 0x00. The way oc-accel logic gathers all bytes of partial reads was so resulting in a full word of 0xFF hiding the valid bytes. We have corrected that filling invalid bytes with 0x00 and tested it successfully.
**Can you please test it and confirm OCSE is now working as on the real hardware?**
go into ocse installation directory, then pull last changes and go into issue10 branch
```
cd ocse
git pull
git checkout issue10
make clean
```
then rebuild a simulation of your design. It will recompile OCSE accordingly 
Once tested, we will merge your code into master branch
thanks a lot

**Comment by rs22** [comment]
Thanks a lot! I can confirm that it now works as expected in my scenario. 😄 👍

**Comment by bmesnet** [comment]
code in #11corrects the issue . Client confirms it is ok. Closing issue and merging the code.
