### ISSUE TITLE
2 successives oc_maint mixes up the MMIO addresses

### ISSUE THREAD

**Issue by bmesnet** [OpenCAPI/ocse#9]
**Issue:** Calling in a script oc_maint twice is seen as multiple context in parallel and so adds an offset to MMIO addresses by creating different PASIDs.
We first get 0x00000014 (PASID = 0) and 0x00400010 (PASID = 1) on the s_axi_ctrl_reg_araddr lines, and later 0x0080001c (PASID = 2) on the s_axi_ctrl_reg_awaddr lines.

**Circumvention:** In OC-Accel, it is not mandatory to call oc_maint before calling an apllication (as it was in SNAP). Calling oc_maint once, or not calling it prevents from hitting the issue.

**Analysis:** This is a ocse specific problem. For some reasons, the 2nd oc_maint  / connection happens too quickly after the first one. (same with 3rd connection of application)
The tlx0 clocks are not stopped yet, so the context is incremented as if there was 2 at the same time.
We use idle_cycles to keep  tlx clock alive after the AFU is idle during 200 cycles and then [stop the clocks ]( https://github.com/OpenCAPI/ocse/blob/master/ocse/ocl.c#L307).
The connection shouldn't be aloud to interrupt this or should reset the clock interruption process
We should have :
```
DEBUG:DETACH request from client context 0 on socket 6
DEBUG:DETACH from client context 0x00
DEBUG:SOCKET OUT:0x06
INFO:9.152.75.200 client disconnect from tlx0 context 0
INFO:Detatched a client: current attached clients = 0        => OCSE_IDLE
DEBUG:tlx_get_afu_events:
DEBUG:tlx_get_afu_events: Just a clock event    <= x200 (TLX_IDLE_CYCLES)
INFO:Stopping clocks to tlx0
ocl->state is 0 	                                                <= OCSE_IDLE meaning attached_clients = 0
        INFO:Connection from 9.152.75.200                <= new connection
        ...../...
	DEBUG:_client_loop: client associated
DEBUG:SOCKET IN:0x05
INFO:Attached client context 0: current attached clients = 1: client type = \00
```
while we have:
```
DEBUG:DETACH request from client context 0 on socket 6
DEBUG:DETACH from client context 0x00
DEBUG:SOCKET OUT:0x06
INFO:172.17.0.2 client disconnect from tlx0 context 0
INFO:Detatched a client: current attached clients = 0       => OCSE_IDLE
DEBUG:tlx_get_afu_events:
DEBUG:tlx_get_afu_events: Just a clock event           <= x6 cycles
        INFO:Connection from 172.17.0.2                           <= new connection
        ...../...
        DEBUG:_client_loop: client associated
DEBUG:tlx_get_afu_events:
DEBUG:tlx_get_afu_events: Just a clock event            <= x194 cycles
INFO:Stopping clocks to tlx0				
DEBUG:SOCKET IN:0x05
INFO:Attached client context 1: current attached clients = 1: client type = \00
```

**Solution**: issue need to be reproduced in simulation before starting correction

**Comment by rs22** [comment]
I have the same issue when running a unit test executable within an ocse simulation. It allocates and releases card handles in quick succession, which yields the described behavior.

My workaround is to sleep for a couple of seconds after each call to `snap_card_free` (oc-accel), but if this is really necessary then this sleep should be integrated into the underlying libocxl method.

**Comment by bmesnet** [comment]
@rs22 I haven't been able to reproduce this issue yet.
Could you try and reduce the value [TLX_IDLE_CYCLES ](https://github.com/OpenCAPI/ocse/blob/9f0001603c08be058a9ca40344f420bfe0a61908/common/utils.h#L37) from 200 to a much smaller value (i.e. 10). I'm not owner of the code but it seems this change should solve your issue without breaking anything. You'll need to do a `make clean `followed by a `make ` in the ocse directory to recompile the ocse. 
All tests done with this value seems ok until now. Thx

**Comment by rs22** [comment]
I have been able to reproduce the problem using oc-accel's `snap_helloworld_1024`: 
```bash
echo "Hello world_1024. This is my first CAPI SNAP experience. It's real fun." > /tmp/t1
for i in {1..10}; do snap_helloworld_1024 -i /tmp/t1 -o /tmp/t2; done
```
Reducing the TLX_IDLE_CYCLES seems to have reduced the likeliness of the simulation getting stuck, but for me it still does not complete the ten invocations.

**Comment by bmesnet** [comment]
Hi @rs22 
Uma was able to change some [code](https://github.com/OpenCAPI/ocse/blob/master/ocse/ocl.c#L338) replacing the if by a while. 
We did a bunch of tests and it seems now ok
Could you test if it now ok? 
Thanks a lot

**Comment by rs22** [comment]
Thanks a lot! This seems to have fixed it! 👍

**Comment by bmesnet** [comment]
Closing issue. Thanks
